### ISSUE TITLE
How do I build this

### ISSUE THREAD

**Issue by Wizi8914** [Marviuz/tower-of-funtasy-discordbot#1]
I tried to launch the code on a bot created for the occasion but do not know how to launch it (I have a .env file with a DISCORD_CLIENT_TOKEN variable with my bot token)

![image](https://user-images.githubusercontent.com/45132525/192584752-3efb925f-8353-4870-ad94-9962c97e24bd.png)

**Comment by Marviuz** [comment]
have you tried to `console.log` your token and see if it reads it?

**Comment by Marviuz** [comment]
maybe you are running it with `npm start` instead of `npm run dev`. The `start` doesn't run with `dotenv` in it.

**Comment by Wizi8914** [comment]
It works now, thanks !
